version: '3.7'

services:
  main:
    container_name: goodtime-node-template
    build:
      context: . #pass in all the files in the current directory to the docker instance
      args:
        - GOODTIME_NPM_TOKEN
      target: development # tells docker to build the 'development' portion of our Dockerfile
    volumes:
      - ./src:/usr/app/src
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${DEBUG_PORT}:9229
    command: npm run dev
    networks:
      - webnet
networks:
  webnet:
