name: test

env:
  GOODTIME_NPM_TOKEN: ${{secrets.GOODTIME_NPM_TOKEN}}

on:
  push:
    branches:
      - main
    # Sequence of patterns matched against refs/heads
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
      -   uses: actions/setup-node@v1
          with:
            node-version: 12.18.4
      -   run: npm ci
      -   run: npm test
